# TRAIN #1

## Data Exploration

โดยชุดข้อมูลนี้ต้องการให้เราทำนายว่าผู้ใช้งาน credit_card จะมีแนวโน้มว่าจะยกเลิก หรือ จะใช้งาน credit_card ต่อไปโดยวิเคราะห์จาก feature ที่มี
จากข้อมูลที่ได้มามี feature ทั้งหมด 23 feature และมี sample ทั้งหมด 10127 คน จากคำแนะนำของชุดข้อมูลได้ทำการลบ 2 feature สุดท้ายออก<br>
แยก feature Attrition_Flag ออกมาเก็บในตัวแปล df_y เหลือชุดข้อมูลในการวิเคราะห์ทั้งหมด 20 feature

In [1]:
import pandas as pd
import seaborn as sns
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import numpy as np
from IPython.display import Image

df = pd.read_csv('credit_card_churn.csv',sep=',')
df.columns = ["CLIENTNUM","Attrition_Flag","Customer_Age","Gender","Dependent_count","Education_Level","Marital_Status","Income_Category","Card_Category","Months_on_book","Total_Relationship_Count","Months_Inactive_12_mon","Contacts_Count_12_mon","Credit_Limit","Total_Revolving_Bal","Avg_Open_To_Buy","Total_Amt_Chng_Q4_Q1","Total_Trans_Amt","Total_Trans_Ct","Total_Ct_Chng_Q4_Q1","Avg_Utilization_Ratio","Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1","Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"]
df_y = df["Attrition_Flag"]
df = df.drop(["Attrition_Flag","Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1","Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2"],axis = 1)
print(df.shape)
df.head()

(10127, 20)


CLIENTNUM  Customer_Age Gender  Dependent_count Education_Level  \
0  768805383            45      M                3     High School   
1  818770008            49      F                5        Graduate   
2  713982108            51      M                3        Graduate   
3  769911858            40      F                4     High School   
4  709106358            40      M                3      Uneducated   

  Marital_Status Income_Category Card_Category  Months_on_book  \
0        Married     $60K - $80K          Blue              39   
1         Single  Less than $40K          Blue              44   
2        Married    $80K - $120K          Blue              36   
3        Unknown  Less than $40K          Blue              34   
4        Married     $60K - $80K          Blue              21   

   Total_Relationship_Count  Months_Inactive_12_mon  Contacts_Count_12_mon  \
0                         5                       1                      3   
1                         6                       1                      2   
2                         4                       1                      0   
3                         3                       4                      1   
4                         5                       1                      0   

   Credit_Limit  Total_Revolving_Bal  Avg_Open_To_Buy  Total_Amt_Chng_Q4_Q1  \
0       12691.0                  777          11914.0                 1.335   
1        8256.0                  864           7392.0                 1.541   
2        3418.0                    0           3418.0                 2.594   
3        3313.0                 2517            796.0                 1.405   
4        4716.0                    0           4716.0                 2.175   

   Total_Trans_Amt  Total_Trans_Ct  Total_Ct_Chng_Q4_Q1  Avg_Utilization_Ratio  
0             1144              42                1.625                  0.061  
1             1291              33                3.714                  0.105  
2             1887              20                2.333                  0.000  
3             1171              20                2.333                  0.760  
4              816              28                2.500                  0.000

โดยชุดข้อมูลของคนที่ใช้ Credit card อยู่ในปัจจุบันมีจำนวน 8500 คน และ ยกเลิก Credit card มีจำนวน 1627 คน<br>
จากการ check ข้อมูลไม่มี missing value ในชุดข้อมูล

In [2]:
print(df_y.value_counts())
print("")
# ดู missing valus
print(df.isnull().sum())
print(df.shape)
# code handmake
# for i in range(0,len(df.columns)):
#     print(df.columns[i] +"\t\t"+ str(df[str(df.columns[i])].isnull().sum()))

Existing Customer    8500
Attrited Customer    1627
Name: Attrition_Flag, dtype: int64

CLIENTNUM                   0
Customer_Age                0
Gender                      0
Dependent_count             0
Education_Level             0
Marital_Status              0
Income_Category             0
Card_Category               0
Months_on_book              0
Total_Relationship_Count    0
Months_Inactive_12_mon      0
Contacts_Count_12_mon       0
Credit_Limit                0
Total_Revolving_Bal         0
Avg_Open_To_Buy             0
Total_Amt_Chng_Q4_Q1        0
Total_Trans_Amt             0
Total_Trans_Ct              0
Total_Ct_Chng_Q4_Q1         0
Avg_Utilization_Ratio       0
dtype: int64
(10127, 20)


## Model Building & Model Training

In [3]:
df_onehot = pd.get_dummies(df)

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_onehot,df_y,test_size = 0.25,random_state = 25)
print(y_train.value_counts())

print("X_train : " +str(X_train.shape))

Existing Customer    6364
Attrited Customer    1231
Name: Attrition_Flag, dtype: int64
X_train : (7595, 38)


Decision tree

In [5]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree = DecisionTreeClassifier(criterion='entropy',)
model_DecisionTree 

DecisionTreeClassifier(criterion='entropy')

In [6]:
# train model
model_DecisionTree.fit(X_train, y_train)
# predict model train
y_pred = model_DecisionTree.predict(X_train)

# Classification report
from sklearn.metrics import classification_report,confusion_matrix
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))
# predict model test
y_pred = model_DecisionTree.predict(X_test)
# predict model train
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))


Classification report 
                   precision    recall  f1-score   support

Attrited Customer       1.00      1.00      1.00      1231
Existing Customer       1.00      1.00      1.00      6364

         accuracy                           1.00      7595
        macro avg       1.00      1.00      1.00      7595
     weighted avg       1.00      1.00      1.00      7595

Confusion matrix 
[[1231    0]
 [   0 6364]]
Classification report 
                   precision    recall  f1-score   support

Attrited Customer       0.82      0.82      0.82       396
Existing Customer       0.97      0.97      0.97      2136

         accuracy                           0.94      2532
        macro avg       0.89      0.89      0.89      2532
     weighted avg       0.94      0.94      0.94      2532

Confusion matrix 
[[ 324   72]
 [  70 2066]]


Random forest

In [7]:
from sklearn.ensemble import RandomForestClassifier
model_RandomForest = RandomForestClassifier(n_estimators=100,criterion='entropy')
model_RandomForest 

RandomForestClassifier(criterion='entropy')

In [8]:
# train model
model_RandomForest.fit(X_train, y_train)
# predict model train
y_pred = model_RandomForest.predict(X_train)
# Classification report
from sklearn.metrics import classification_report,confusion_matrix
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))

# predict model train
y_pred = model_RandomForest.predict(X_test)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))


Classification report 
                   precision    recall  f1-score   support

Attrited Customer       1.00      1.00      1.00      1231
Existing Customer       1.00      1.00      1.00      6364

         accuracy                           1.00      7595
        macro avg       1.00      1.00      1.00      7595
     weighted avg       1.00      1.00      1.00      7595

Confusion matrix 
[[1231    0]
 [   0 6364]]
Classification report 
                   precision    recall  f1-score   support

Attrited Customer       0.91      0.81      0.86       396
Existing Customer       0.97      0.99      0.98      2136

         accuracy                           0.96      2532
        macro avg       0.94      0.90      0.92      2532
     weighted avg       0.96      0.96      0.96      2532

Confusion matrix 
[[ 322   74]
 [  30 2106]]


In [9]:
model_RandomForest = RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=10)
model_RandomForest 
# train model

model_RandomForest.fit(X_train, y_train)
# predict model train
y_pred = model_RandomForest.predict(X_train)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))

# predict model test
y_pred = model_RandomForest.predict(X_test)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))

Classification report 
                   precision    recall  f1-score   support

Attrited Customer       0.98      0.89      0.93      1231
Existing Customer       0.98      1.00      0.99      6364

         accuracy                           0.98      7595
        macro avg       0.98      0.94      0.96      7595
     weighted avg       0.98      0.98      0.98      7595

Confusion matrix 
[[1095  136]
 [  27 6337]]
Classification report 
                   precision    recall  f1-score   support

Attrited Customer       0.90      0.73      0.81       396
Existing Customer       0.95      0.98      0.97      2136

         accuracy                           0.95      2532
        macro avg       0.92      0.86      0.89      2532
     weighted avg       0.94      0.95      0.94      2532

Confusion matrix 
[[ 291  105]
 [  34 2102]]


K_Nearest_Neighbor

In [10]:
#import machine learning library
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
model_knn = knn.fit(X_train, y_train)

In [11]:
# predict model train
y_pred = model_knn.predict(X_train)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))

# predict model test
y_pred = model_knn.predict(X_test)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))

Classification report 
                   precision    recall  f1-score   support

Attrited Customer       0.72      0.36      0.48      1231
Existing Customer       0.89      0.97      0.93      6364

         accuracy                           0.87      7595
        macro avg       0.80      0.67      0.70      7595
     weighted avg       0.86      0.87      0.86      7595

Confusion matrix 
[[ 446  785]
 [ 176 6188]]
Classification report 
                   precision    recall  f1-score   support

Attrited Customer       0.17      0.09      0.12       396
Existing Customer       0.84      0.92      0.88      2136

         accuracy                           0.79      2532
        macro avg       0.51      0.50      0.50      2532
     weighted avg       0.74      0.79      0.76      2532

Confusion matrix 
[[  37  359]
 [ 181 1955]]


# TRAIN #2

# Data preprocessing

แยกชุดข้อมูลประเภท numeric and Categorical และเพื่ม y ที่เปลี่ยนข้อมูลจาก["Existing Customer","Attrited Customer"] เป็น [1,0] เข้าไปในข้อมูลทั้ง 2 ประเภท<br> 

In [12]:
# df_y = pd.get_dummies(df_y)
df_y = df_y.replace(["Existing Customer","Attrited Customer"],[1,0])
print(df_y.value_counts())


1    8500
0    1627
Name: Attrition_Flag, dtype: int64


In [13]:

df_class = df.select_dtypes(object)
df_numer = df.drop(df_class.columns,axis= 1)

# เพื่ม y 
df_class = df_class.join([df_y])
df_numer = df_numer.join([df_y])
print("numeric : "+str(df_numer.shape))
print("class : "+str(df_class.shape))
# df_numer = df.drop(df_class.columns)


numeric : (10127, 16)
class : (10127, 6)


one-hot ข้อมูลประเภท Categorical ในอยู่ในแบบใน numeric 

In [14]:
df_class = pd.get_dummies(df_class)
print(len(df_class.shape))
# print(len(df_class.columns))

2


Plot heatmap numeric

In [15]:
# corr = df_numer.corr()
# mask = np.array(corr)
# # print(corr)
# mask[np.tril_indices_from(mask)] = False     
# fig,ax = plt.subplots()
# fig.set_size_inches(10,5)
# sns.heatmap(corr,mask= mask,vmax =1,vmin = -1,annot= True,cmap= 'coolwarm')
Image(url="pic/heatmap numeric.png", width=300, height=300)

Plot heatmap Categorical

In [16]:
# corr = df_class.corr()
# mask = np.array(corr)
# # print(corr)
# mask[np.tril_indices_from(mask)] = False     
# fig,ax = plt.subplots()
# fig.set_size_inches(10,5)
# sns.heatmap(corr,mask= mask,vmax =1,vmin =-1,annot= True,cmap= 'coolwarm')
Image(url="pic/heatmap classification.png", width=300, height=300)

Pairplot numeric

In [17]:
# sns.pairplot(df_class,hue="Attrition_Flag")
Image(url="pic/pairplot classification.png", width=300, height=300)

Pairplot Categorical

In [18]:
# sns.pairplot(df_numer,hue="Attrition_Flag")
Image(url="pic/pairplot numeric.png", width=300, height=300)

In [19]:
Image(url="pic/pairplot highlight.png", width=300, height=300)

จากการ pairplot ข้อมูลประเภท numeric มาว่ามีช่วงที่มีการแบ่งกลุ่มอย่างชัดเจนในช่วงสีแดง และสีฟ้า

ผมจึงได้เลือก feature ในข้อมูลประเภท numeric ดังนี้
* Credit_Limit 
* Total_Revolving_Bal
* Avg_Open_To_Buy
* Total_Amt_Chng_Q4_Q1
* Total_Trans_Amt
* Total_Trans_Ct
* Total_Ct_Chng_Q4_Q1
* Avg_Utilization_Ratio
* Attrition_Flag

In [20]:
df_numer = df_numer.drop([
    'CLIENTNUM', 
    'Customer_Age', 
    'Dependent_count', 
    'Months_on_book',
    'Total_Relationship_Count', 
    'Months_Inactive_12_mon',
    'Contacts_Count_12_mon'],axis = 1)
print(df_numer.shape)
print(df_numer.columns)
print(str(df_numer.columns[1]))

(10127, 9)
Index(['Credit_Limit', 'Total_Revolving_Bal', 'Avg_Open_To_Buy',
       'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct',
       'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio', 'Attrition_Flag'],
      dtype='object')
Total_Revolving_Bal


In [21]:
Image(url="pic/heatmap highlight.png", width=300, height=300)

จากการทำ heatmap ข้อมูลประเภท Categorical พบว่าข้อมูลช่วงสีแดงเป็นข้อมูลที่มีความสัมพันธ์กัน

ผมจึงได้เลือกใช้ feature ประเภท classificaltion ดังนี้
* Gender
* Income_Category

In [22]:

df_class = pd.get_dummies(df[["Gender","Income_Category"]])
print("df_class : "+str(df_class.shape))

df_full = df_numer.join([df_class])
df_full = df_full.drop("Attrition_Flag",axis=1)
print(df_full.shape)
print(df_full.columns)

df_class : (10127, 8)
(10127, 16)
Index(['Credit_Limit', 'Total_Revolving_Bal', 'Avg_Open_To_Buy',
       'Total_Amt_Chng_Q4_Q1', 'Total_Trans_Amt', 'Total_Trans_Ct',
       'Total_Ct_Chng_Q4_Q1', 'Avg_Utilization_Ratio', 'Gender_F', 'Gender_M',
       'Income_Category_$120K +', 'Income_Category_$40K - $60K',
       'Income_Category_$60K - $80K', 'Income_Category_$80K - $120K',
       'Income_Category_Less than $40K', 'Income_Category_Unknown'],
      dtype='object')


## Model Building & Model Training

In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df_full,df_y,test_size = 0.25,random_state = 25)
print(y_train.value_counts())

print("X_train : " +str(X_train.shape))

1    6364
0    1231
Name: Attrition_Flag, dtype: int64
X_train : (7595, 16)


Decision tree

In [24]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree = DecisionTreeClassifier(criterion='entropy',)
model_DecisionTree 

DecisionTreeClassifier(criterion='entropy')

In [25]:
# train model
model_DecisionTree.fit(X_train, y_train)
# predict model train
y_pred = model_DecisionTree.predict(X_train)

# Classification report
from sklearn.metrics import classification_report,confusion_matrix
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))
# predict model test
y_pred = model_DecisionTree.predict(X_test)
# predict model train
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))


Classification report 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1231
           1       1.00      1.00      1.00      6364

    accuracy                           1.00      7595
   macro avg       1.00      1.00      1.00      7595
weighted avg       1.00      1.00      1.00      7595

Confusion matrix 
[[1231    0]
 [   0 6364]]
Classification report 
              precision    recall  f1-score   support

           0       0.81      0.77      0.79       396
           1       0.96      0.97      0.96      2136

    accuracy                           0.94      2532
   macro avg       0.88      0.87      0.87      2532
weighted avg       0.93      0.94      0.93      2532

Confusion matrix 
[[ 305   91]
 [  73 2063]]


Random forest

In [26]:
from sklearn.ensemble import RandomForestClassifier
model_RandomForest = RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=10)
model_RandomForest 

RandomForestClassifier(criterion='entropy', max_depth=10)

In [27]:
# train model
model_RandomForest.fit(X_train, y_train)
# predict model train
y_pred = model_RandomForest.predict(X_train)
# Classification report
from sklearn.metrics import classification_report,confusion_matrix
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))

# predict model train
y_pred = model_RandomForest.predict(X_test)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))


Classification report 
              precision    recall  f1-score   support

           0       0.97      0.91      0.94      1231
           1       0.98      0.99      0.99      6364

    accuracy                           0.98      7595
   macro avg       0.98      0.95      0.96      7595
weighted avg       0.98      0.98      0.98      7595

Confusion matrix 
[[1119  112]
 [  37 6327]]
Classification report 
              precision    recall  f1-score   support

           0       0.87      0.78      0.83       396
           1       0.96      0.98      0.97      2136

    accuracy                           0.95      2532
   macro avg       0.92      0.88      0.90      2532
weighted avg       0.95      0.95      0.95      2532

Confusion matrix 
[[ 310   86]
 [  45 2091]]


ยัง overfining อยู่ ใช้ grid_serarch ในการปรับ parameter

In [28]:
from sklearn.model_selection import GridSearchCV
param_grid = {"n_estimators":[100,150,200],"max_depth":[10]}
grid_search = GridSearchCV(RandomForestClassifier(), param_grid)
grid_search.fit(X_train, y_train)
print('Best params : {}'.format(grid_search.best_params_))
print('Accuracy of trainning set:{:.2f}'.format(grid_search.score(X_train, y_train)))
print('Accuracy of testing set:{:.2f}'.format(grid_search.score(X_test, y_test)))

Best params : {'max_depth': 10, 'n_estimators': 100}
Accuracy of trainning set:0.98
Accuracy of testing set:0.95


In [29]:
model_RandomForest = RandomForestClassifier(n_estimators=200,criterion='entropy',max_depth=10)
model_RandomForest 
# train model

model_RandomForest.fit(X_train, y_train)
# predict model train
y_pred = model_RandomForest.predict(X_train)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))

# predict model test
y_pred = model_RandomForest.predict(X_test)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))

Classification report 
              precision    recall  f1-score   support

           0       0.97      0.91      0.94      1231
           1       0.98      0.99      0.99      6364

    accuracy                           0.98      7595
   macro avg       0.98      0.95      0.96      7595
weighted avg       0.98      0.98      0.98      7595

Confusion matrix 
[[1124  107]
 [  35 6329]]
Classification report 
              precision    recall  f1-score   support

           0       0.88      0.77      0.82       396
           1       0.96      0.98      0.97      2136

    accuracy                           0.95      2532
   macro avg       0.92      0.88      0.90      2532
weighted avg       0.95      0.95      0.95      2532

Confusion matrix 
[[ 305   91]
 [  42 2094]]


K_Nearest_Neighbor

In [30]:
#import machine learning library
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
model_knn = knn.fit(X_train, y_train)
print('Accuracy of trainning set:{:.2f}'.format(model_knn.score(X_train, y_train)))
print('Accuracy of testing set:{:.2f}'.format(model_knn.score(X_test, y_test)))

Accuracy of trainning set:0.93
Accuracy of testing set:0.89


In [31]:
knn = KNeighborsClassifier(n_neighbors=3)
model_knn = knn.fit(X_train, y_train)
# predict model train
y_pred = model_knn.predict(X_train)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_train, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_train, y_pred=y_pred))

# predict model test
y_pred = model_knn.predict(X_test)
# Classification report
print("Classification report \n=======================")
print(classification_report(y_true=y_test, y_pred=y_pred))
print("Confusion matrix \n=======================")
print(confusion_matrix(y_true=y_test, y_pred=y_pred))

Classification report 
              precision    recall  f1-score   support

           0       0.83      0.75      0.79      1231
           1       0.95      0.97      0.96      6364

    accuracy                           0.93      7595
   macro avg       0.89      0.86      0.87      7595
weighted avg       0.93      0.93      0.93      7595

Confusion matrix 
[[ 921  310]
 [ 186 6178]]
Classification report 
              precision    recall  f1-score   support

           0       0.69      0.59      0.64       396
           1       0.93      0.95      0.94      2136

    accuracy                           0.89      2532
   macro avg       0.81      0.77      0.79      2532
weighted avg       0.89      0.89      0.89      2532

Confusion matrix 
[[ 234  162]
 [ 104 2032]]
